GFOL/Controllers/FormController.cs
using System;
using System.Linq;
using GFOL.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GFOL.Services;

namespace GFOL.Controllers
{
    public class FormController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFormService _formService;
        private readonly ISubmissionService _submissionService;
        private readonly ISessionService _sessionService;
        private readonly IGFOLValidation _gfolValidation;
        public FormController(ILogger<HomeController> logger, IFormService formService, ISubmissionService submissionService, ISessionService sessionService, IGFOLValidation gfolValidation)
        {
            _logger = logger;
            _formService = formService;
            _submissionService = submissionService;
            _sessionService = sessionService;
            _gfolValidation = gfolValidation;
        }
        /// <summary>
        /// This action is called from the address controller
        /// after the user has selected an address from the address finder list
        /// </summary>
        /// <param name="address"></param>
        /// <param name="nextPageId"></param>
        /// <returns>redirects to the index page to load the full address question</returns>
        [HttpGet]
        public IActionResult SelectAddress(string address, string nextPageId)
        {
            try
            {
                //go and get the address page
                var pageVm = _formService.GetPageById(nextPageId);
                //store the full address in session
                foreach (var question in pageVm.Questions)//there's only one
                {
                    question.Answer = address;
                    _submissionService.SaveUserAnswerIntoSession(question);
                }

                return RedirectToAction("Index", new { id = nextPageId });
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }
        /// <summary>
        /// THis action shows the question page
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index(string id = "")
        {
            try
            {
                var referer = Request.Headers["Referer"].ToString();
                if (string.IsNullOrWhiteSpace(referer))
                {
                    //url entered into the browser
                    return RedirectToAction("PageNotFound", "Error");
                }
                //flag if user has come back from check your answers
                if (referer.ToLower().Contains("checkyouranswers"))
                {
                    _sessionService.SetUserComeFromCheck();
                }
                if (id == "start")
                {
                    return RedirectToAction("Index", "Home");
                }
                var pageVm = _formService.GetPageById(id);
                //load any existing answers from the session
                foreach (var question in pageVm.Questions)
                {
                    var answer = _submissionService.GetUserAnswerFromSession(question.QuestionId);
                    question.Answer = answer;
                }
                return View(pageVm);

            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }
        /// <summary>
        /// this action validates and stores the user response and direct the flow to the next question page
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(PageVM vm)
        {
            try
            {
                //Get the page we are validating
                var pageVm = _formService.GetPageById(vm.PageId);
                foreach (var question in vm.Questions)
                {
                    //put in the answers from the page
                    pageVm.Questions.FirstOrDefault(x => x.QuestionId == question.QuestionId).Answer = question.Answer;
                }
                //Validate the Response against the page json
                _gfolValidation.ValidatePage(pageVm);

                //Get any errors
                if (pageVm.Questions.Any(x => x.Validation.IsErrored || x.Validation.Required.IsErrored || x.Validation.StringLength.IsErrored))
                {
                    return View(pageVm);
                }
                //store answer/s in session
                foreach (var question in vm.Questions)
                {
                    _submissionService.SaveUserAnswerIntoSession(question);
                }
                //if this is a postcode then get a list of addresses
                var postcodeQuestion = pageVm.Questions.FirstOrDefault(x => x.DataType.ToLower() == "postcode");
                if (postcodeQuestion != null)
                {
                    var postcode = postcodeQuestion?.Answer;
                    return RedirectToAction("Index", "Address", new { postcode = postcode, pageId = pageVm.PageId, nextPageId = pageVm.NextPageId });
                }
                //redirect to the Index page with our new PageId
                var nextPageId = pageVm.NextPageId;
                if (nextPageId == "checkyouranswers" || _sessionService.HasUserComeFromCheck())
                {
                    return RedirectToAction("Index", "CheckYourAnswers");
                }
                else
                {
                    return RedirectToAction("Index", new { id = nextPageId });
                }

            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }
    }
}

GFOL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GFOL.Models;
using GFOL.Services;

namespace GFOL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ISessionService _sessionService;

        public HomeController(ILogger<HomeController> logger, ISessionService sessionService)
        {
            _logger = logger;
            _sessionService = sessionService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                _sessionService.ClearSession();
                return View();
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GFOL/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GFOL.Models;
using GFOL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GFOL.Controllers
{
    [Authorize]
    public class SubmissionController : Controller
    {
        private readonly ILogger<SubmissionController> _logger;
        private readonly ISubmissionService _submissionService;

        public SubmissionController(ILogger<SubmissionController> logger, ISubmissionService submissionService)
        {
            _logger = logger;
            _submissionService = submissionService;
        }
        //this action gets all the saved submissions and displays them in the page
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var submissions = await _submissionService.GetAllSubmissionsAsync();
                var model = new ViewSubmissionsVM { Submissions = submissions };
                return View(model);
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }
        [HttpGet]
        public async Task<IActionResult> ViewSubmission(int id)
        {
            try
            {
                var model = await _submissionService.GetSubmissionAsync(id);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e.Message, e);
                return RedirectToAction("ProblemWithService", "Error");//Todo let middleware deal with errors
            }
        }
    }
}

GFOL/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Home Page";
}
<gfol-container>
    <gfol-breadcrumb>
        <gfol-breadcrumb-list>
            <gfol-breadcrumb-list-item>
                <partial name="_LoginPartial" />
            </gfol-breadcrumb-list-item>
        </gfol-breadcrumb-list>
    </gfol-breadcrumb>

    <gfol-main-wrapper>
        <gfol-row>
            <gfol-column desktop-size="TwoThirds" tablet-size="FullWidth">
                <gfol-heading heading-type="H1" text="Give Feedback On Lighting"></gfol-heading>
                <gfol-paragraph>Use this service to tell us about:</gfol-paragraph>

                <gfol-list list-type="Bullet">
                    <li>the quality of the lighting outside your home</li>
                    <li>a concern you have about the level of light</li>
                    <li>if you are happy with the lighting outside your home</li>
                </gfol-list>

                <a asp-controller="Form" asp-action="Index">
                    <gfol-paragraph><gfol-button button-status="Enabled" button-text="Start Now >" button-type="Submit" start-now="true"></gfol-button></gfol-paragraph>
                </a>
                @*<a asp-controller="Form" asp-action="Index" role="button" draggable="false" class="govuk-button govuk-!-margin-top-2 govuk-!-margin-bottom-8 govuk-button--start" data-module="govuk-button">
                    Start now
                    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
                        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
                    </svg>
                </a>*@
                <gfol-heading heading-type="H3" text="Before you start"></gfol-heading>

                <gfol-paragraph>The online service is also available in <a class="govuk-link" href="#">Welsh (Cymraeg)</a>.</gfol-paragraph>

                <gfol-paragraph>You cannot register for this service if you’re in the UK illegally.</gfol-paragraph>
            </gfol-column>

            <gfol-column desktop-size="OneThird " tablet-size="FullWidth">

                <!-- The Related items component is not part of GOV.UK Frontend but will be styled if used in the Prototype Kit -->

                <aside class="app-related-items" role="complementary">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <gfol-heading heading-type="H3" text="Admin Tasks"></gfol-heading>
                        <nav role="navigation" aria-labelledby="subsection-title">
                            <gfol-list list-type="Normal">
                                <li>
                                    <a class="govuk-link" asp-action="Index" asp-controller="Submission">
                                        View Submissions
                                    </a>
                                </li>
                            </gfol-list>
                        </nav>
                    }
                    else
                    {
                        <gfol-heading heading-type="H3" text="Related Links"></gfol-heading>
                        <nav role="navigation" aria-labelledby="subsection-title">
                            <gfol-list list-type="Normal">
                                <li>
                                    <a class="govuk-link" href="#">
                                        Fab Lighting
                                    </a>
                                </li>
                                <li>
                                    <a class="govuk-link" href="#">
                                        Lamp Posts R Us
                                    </a>
                                </li>
                            </gfol-list>
                        </nav>
                    }
                </aside>

            </gfol-column>

        </gfol-row>

    </gfol-main-wrapper>

</gfol-container>